stages:
  - configure
  - lint
  - build
  - test
  - documentation
  - package


lint:rustfmt:
  stage: lint
  image: rust:latest
  before_script:
    - rustup component add rustfmt
  script:
    - cargo fmt --all -- --check
  allow_failure: true


lint:clippy:
  stage: lint
  image: rust:latest
  before_script:
    - rustup component add clippy
  script:
    - cargo clippy --all-targets --all-features
  allow_failure: true


build:cargo:
  stage: build
  image: rust:latest
  script:
    - cargo build --bins --tests
  artifacts:
    paths:
      - 'target/debug/'


test:cargo:
  stage: test
  image: rust:latest
  script:
    - cargo test
  dependencies:
    - build:cargo
